"""removed badge column for stest

Revision ID: 7a22bfb5841f
Revises: c182549c4320
Create Date: 2025-10-23 11:07:07.704434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a22bfb5841f'
down_revision = 'c182549c4320'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM   pg_constraint
        WHERE  conname = 'uq_user_badge'
        AND    conrelid = 'user_badges'::regclass
      ) THEN
        ALTER TABLE user_badges
        ADD CONSTRAINT uq_user_badge UNIQUE (user_id, badge_id);
      END IF;
    END$$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_badge', type_='unique')

    # ### end Alembic commands ###
